### PR TITLE
Executable graphql server with user auth queries and mutations

### PR DESCRIPTION
**Pull request by wiarda**
Working graphql server with basic implementation of user auth queries and mutations
May need to add some validation if we're not doing that on the express server

### CODE REVIEW

**Comment by mawarijo** [comment]
This is looking great! Super awesome you took on learning both GraphQL and PostgreSQL for this. Your reducer implementation seems to be good - let me clone and check it to be sure though. Just a couple suggestions in the type defs I was thinking:
Queries:
`getUser` => `user`
`authenticateUser` => `authUser`
`Users` => `users`
Mutations:
`UserMutationResponse { ..., user: User }` => `{ ..., user: User! }`

**Comment by mawarijo** [comment]
Let's also make `code` and `message` inside of `UserMutationResponse` into enums:
```js
enum CodeType {
  200
  400
  ...
}

enum MessageType {
  NOT_FOUND
  NOT_PERMITTED
  ...
}
```
or however you've set them up. Would that work?

**Comment by wiarda** [comment]
I've 
-renamed the queries
-added a response code enum

On further reflection, I don't think we should make a MessageType enum, because that will get in the way of writing expressive error messages. 

The error code should be sufficient for standardizing the type of the error, while leaving the message open will allow us to customize or explain more in a human readable format without worrying about adhering to a few basic responses.

**Comment by mawarijo** [comment]
Thanks for the updates, I agree with your decisions.

**Pull request merged**
