### PR TITLE
Build setup

### PR DESCRIPTION
**Pull request by awiw642**
* Separating webpack config to webpack.dev and webpack.prod
* Removes unused styles.css from index.html
* Rebuild index.html during the build process. This is so we can rename our bundle.js everytime we build to reset cache for the deployment. The renaming part of bundle.js is not completed yet.

### CODE REVIEW

**Comment by mawarijo** [comment]
Good changes so far. Before we merge this could you go ahead and set up our Heroku deployment? Instructions are here if you need them: https://devcenter.heroku.com/articles/getting-started-with-nodejs#set-up. You'll need to specify our Node environment in package.json, add a Heroku-postbuild script, and set up any env variables in our Heroku app's settings (I don't think we've got any yet though).

**Comment by wiarda** [comment]
We do have a some db settings that should go into .env (you can find them in the graphql channel on discord). 

They may not be necessary if we're not hosting the graphql server on heroku

**Comment by awiw642** [comment]
Nope, clean-webpack-plugin is just to clear everything in the build directory. This is because I plan to rename our bundle.js which is the compilation of the client to be bundle.<hash>.js. The reason why I want to rename the bundle file is to make sure that the client starts with a fresh cache every time we create a new build.

**Comment by mawarijo** [comment]
I can finish up the Heroku deployment if you're not able to, @awiw642 but if you had a specific webpack configuration in mind it'd be great if you could just finish that up before we merge it? Let me know when that's done and I'll merge it.

**Comment by awiw642** [comment]
Hello @mawarijo,

I think I have covered all the webpack config that I can think off right now. Another one that might be good is to minify css. But I personally never used it before and performance is still good. If the css size becomes a problem in the future, we can then include this.

As for plugin, I have only set up a few:
1. CleanWebpackPlugin to clear our public directory where we store our distribution assets.
2. HtmlWebpackPlugin to create a new html everytime. This helps especially with the created bundle containing hash. This will attach the bundle to the html automatically.
3. HotModuleReplacementPlugin, which we all love!


That's all for webpack config. I am not able to finish the heroku config. Be back in 2 weeks. Let me know if you guys still need a hand by then.

**Pull request merged**
